### ISSUE TITLE
[Feature Request] Compat with Storage Drawers

### ISSUE THREAD

**Issue by Silvrus** [Shadows-of-Fire/Wither-Skeleton-Tweaks#10]
Loving this mod, if for nothing else than the removal of regular skelly spawns and stone swords. I discovered however that in 1.12.2 the skull fragments don't compact down to skulls in Storage Drawers Compacting Drawers. Not sure if this is something you can fix or if Storage Drawers needs to. Thanks for the great mod, and thanks for looking into this.

**Comment by Shadows-of-Fire** [comment]
Not sure whose end that is not working in compacting drawers is on.  The default recipe is a 3x3 shapeless, but the config allows you to change the number of fragments needed for a single skull, which, if not 9 or 4, would not work in a compacting drawer.  However, assuming the default, it should be working.  
@jaquadro Anything that can be done about that?
