### ISSUE TITLE
Killing normal skeletons with a blazing immolation blade drops a wither skull.

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Wither-Skeleton-Tweaks#20]
How to recreate issue:
1) Create a new world, get a blazing immolation blade.
2) Kill a regular skeleton with it, check what it drops.

Expected result:
Regular skeletons should not drop wither skulls when killed.

Actual result:
Regular skeletons drop wither skulls instead when killed.

Minecraft 1.14.4
Forge 28.1.40
WitherSkeletonTweaks 3.1.0

**Comment by DinnerBeef** [comment]
this also is for 1.15.4. 
Do you plan on fixing this bug?

**Comment by Shadows-of-Fire** [comment]
This isn't a bug, the sword emulates the avaritia skullfire sword
