### ISSUE TITLE
Wither Skulls uncraftable (but only in a single world file)

### ISSUE THREAD

**Issue by gloomyMoron** [Shadows-of-Fire/Wither-Skeleton-Tweaks#21]
* **Modpack Version**: FTB Omnia 1.6.1/1.7.0

* **Issue**: [Attempting to craft Wither Skeleton Skulls but being unable to.](https://imgur.com/a/npS82IO)

I was unable to use 9 Fragments to craft a Wither Skeleton Skull, despite it being a valid JEI recipe. I created a test world on a clean install of the pack, and the crafting recipe worked. I transferred that save into my modified version. The recipe still works. I created a new test world on my modified version. The recipe works. I went back to my original save, the recipe doesn't work.

Is there a recipe file or some such that is in the World's Save that could have possibly been messed up?

I posted about this on the FTB Omnia issue tracker, and they have no idea and suggested I try elsewhere.

**Comment by Shadows-of-Fire** [comment]
I have no idea, it might've been related to some weird placebo issues that were happening a while ago?  But those were really only happening on 1.16 (I never received reports of them for 1.15).  Anyhow, if it's not reproducible there's not much to be done about it.

**Comment by Peca21** [comment]
Same here custom modpack. 1.16.5

**Comment by SirPeteThe1st** [comment]
I'm also getting this problem of broken Wither Skeleton fragments, and this is the 1.18.2 version. I suggest you re-open this issue and review.
