### ISSUE TITLE
immolation Blades OP - Make droprate configurable

### ISSUE THREAD

**Issue by Raycoms** [Shadows-of-Fire/Wither-Skeleton-Tweaks#24]
Immolation blades have a guaranteed chance for heads which allows players to farm way too many heads in a short period of time.
Is there a way to reduce the drop-rate significantly?

**Comment by Shadows-of-Fire** [comment]
No, there's no config, the purpose of the blades is to guarantee a drop (mimicing a skullfire sword from avaritia)
