### ISSUE TITLE
[1.19.2-8.0.0] Config file seems to not be read properly server-side

### ISSUE THREAD

**Issue by FJDoell** [Shadows-of-Fire/Wither-Skeleton-Tweaks#33]
When making changes to Immolation Blade damage and attack speed (I changed it to -2.4 speed modifier, and 9 bonus damage) it had no affect serverside. This was in an already-existing world, but in singleplayer the configs worked fine.

**Comment by Shadows-of-Fire** [comment]
Config changes must be reflected on the client as well, they cannot be changed solely on the server side (these values are only read on startup).
