### ISSUE TITLE
[1.19.2-8.0.0 Crash] ConcurrentModificationException: Ticking Entity

### ISSUE THREAD

**Issue by FJDoell** [Shadows-of-Fire/Wither-Skeleton-Tweaks#34]
Honestly I'm not sure if it's this mod specifically (likely a combination), but this didn't start occurring until after I added Wither Skeleton Tweaks to the modpack.

Environment: Server/SMP
Forge Version: 43.1.52

Issue: ConcurrentModificationException: null, ticking entity. Wither Skeleton entity.

"Recreation": Occurs randomly in the Nether, so it's hard to recreate.

**Crash Report:** https://pastebin.com/XCFkiREm

I did some small standalone testing as well, with Attribute Fix, Epic Knights, Hostile Mobs and Girls (HMaG), Infernal Mobs, and Placebo of course. Confirmed the following:
- HMaG Girl Skeletons spawn as Wither Skeletons, no apparent issues.
- Infernal Mobs spawn fine and seem to work.
- Piglins attack transformed skeletons fine. It said MobGoals, so I thought maybe this was it.

**Comment by Shadows-of-Fire** [comment]
This CME is coming out of the goal selector, which WST doesn't mess with.

Given that, WST is not a probable cause of the issue being seen here, which is mob goals being modified by two threads at once.
