### ISSUE TITLE
Config file doesnt seem to work- doesnt remove swords

### ISSUE THREAD

**Issue by Lothrazar** [Shadows-of-Fire/Wither-Skeleton-Tweaks#4]
When i try to remove the swords, they are still registered in game, i still find them in JEI and creative menu

:"Enable Blaze Immolation Blade"=false
"Enable Lava Immolation Blade"=false

PS really cool mod, especially the 'delete stone swords' option, thats fantastic.

**Comment by Shadows-of-Fire** [comment]
Yeah, as of now the cfgs just disable the recipes. I mean, I *can* move it... But it should still be working.
