### ISSUE TITLE
Can't disable Fragment Drops: OutOfBounds error

### ISSUE THREAD

**Issue by Mohron** [Shadows-of-Fire/Wither-Skeleton-Tweaks#5]
Wither Skeleton Tweaks-1.11.2-1.6.2

Fragment Drop Chance will cause a crash is set to 0. Please make it possible to disable the drops completely by setting the drop chance to < 1.

**Comment by Shadows-of-Fire** [comment]
Added in 1.7.0

**Comment by Mohron** [comment]
Thank you!
