### ISSUE TITLE
Crash 1.12 (game won't start)

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Wither-Skeleton-Tweaks#7]
[crash-2017-06-15_14.27.15-client.txt](https://github.com/Shadows-of-Fire/Wither-Skeleton-Tweaks/files/1077423/crash-2017-06-15_14.27.15-client.txt)
used forge 2327

**Comment by Shadows-of-Fire** [comment]
Yeah, known issue.  Will push a build shortly, has to be recompiled on latest forge.

**Comment by ghost** [comment]
hey ah, it crashes with forge 2333
[crash-2017-06-17_21.55.50-client.txt](https://github.com/Shadows-of-Fire/Wither-Skeleton-Tweaks/files/1082708/crash-2017-06-17_21.55.50-client.txt)

**Comment by Shadows-of-Fire** [comment]
bleh
