### ISSUE TITLE
Blaze Spawner Nether Issues

### ISSUE THREAD

**Issue by jsaggers** [Shadows-of-Fire/Wither-Skeleton-Tweaks#8]
Not a crash but with Wither Skeleton Tweaks installed a blaze spawner spawns hundreds of wither skeletons, with your mod removed all is good.

Minecraft 1.12
Tried a few Forge versions and using 14.21.1.2400

![with-skeleton-tweaks](https://user-images.githubusercontent.com/11579450/28201527-d31bc3c4-68b4-11e7-85e7-f3061f788ac8.jpg)

**Comment by Shadows-of-Fire** [comment]
This is technically the result of a config option.  But, due to a very recent forge change, I think i can stop them spawning at a spawner like that.

**Comment by jsaggers** [comment]
There was around 500 plus within a few seconds, the image above is what I captured in peaceful mode which they spawn in then disappear.
I mean a wither skeleton spawner would be amazing but that was a little excess :)
