### ISSUE TITLE
[1.12] Skeleton Spawners not Forcing Wither Versions

### ISSUE THREAD

**Issue by MokahTGS** [Shadows-of-Fire/Wither-Skeleton-Tweaks#9]
I've got a mod Nether Ex that adds dungeons to the Nether and the skeleton spawners in those dungeons do not force the skeletons spawned to be the Wither version, even when its set that way in the configs and by the mod.

**Comment by PapiDimmi** [comment]
Spawner spawning isn’t the same as natural spawning.

**Comment by ghost** [comment]
Spawner spawning isn’t the same as natural spawning.

This mod isn’t supposed to replace skeletons in spawners. A skeleton spawner is a skeleton spawner.

Maybe you should speak to the NetherEx devs and get them to change the skeleton spawners to wither skeleton spawners instead.

**Comment by Shadows-of-Fire** [comment]
The mod will not force skeleton spawners to turn into wither skeletons.
